var EMPREENDIMENTOS = [
  {
    "nome": "Vivaz Penha 2",
    "bairro": "Penha (Zona Leste)",
    "endereco": "Avenida Condessa Elisabeth de Robiano, 6000",
    "area": "De 24m² a 38m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de vaga e varanda",
    "lazer": "Piscina, Academia, Espaço Camarote, Lavanderia, Minimercado.",
    "preco": "205mil",
    "entrega": "Nov/2028",
    "imagem": "assets/images/empreendimentos/Vivaz Penha.jpg",
    "lat": -23.5300813,
    "lng": -46.5945978
  },
  {
    "nome": "Vivaz Estação Lapa",
    "bairro": "Lapa (Zona Oeste)",
    "endereco": "Rua Professor Clemente Pastore, 14",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Lazer completo, fácil acesso ao trem/terminal.",
    "preco": "214mil",
    "entrega": "Lançamento",
    "imagem": "assets/images/empreendimentos/Vivaz Estacao Lapa.jpg",
    "lat": -23.51383,
    "lng": -46.69922
  },
  {
    "nome": "Grand Vivaz Jardim França Paris",
    "bairro": "Jardim França",
    "endereco": "Avenida Água Fria, 1215",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Localização residencial privilegiada na Zona Norte.",
    "preco": "224mil",
    "entrega": "Mai/2029",
    "imagem": "assets/images/empreendimentos/Grand Vivaz Jardim Franca.jpg",
    "lat": -23.4780682,
    "lng": -46.6211741
  },
  {
    "nome": "Vivaz Selection Santo Amaro",
    "bairro": "Santo Amaro",
    "endereco": "Rua Doutor Rubens Gomes Bueno, 158",
    "area": "De 24m² a 40m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Localização estratégica próxima a centros comerciais.",
    "preco": "218mil",
    "entrega": "Jan/2029",
    "imagem": "assets/images/empreendimentos/Vivaz Selection Santo Amaro.jpg",
    "lat": -23.6435906,
    "lng": -46.7189299
  },
  {
    "nome": "Vivaz Selection Laguna",
    "bairro": "Granja Julieta",
    "endereco": "Rua Laguna, 440",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de vaga e varanda",
    "lazer": "Próximo à Marginal Pinheiros e Parque Bruno Covas.",
    "preco": "235mil",
    "entrega": "Ago/2028",
    "imagem": "assets/images/empreendimentos/Vivaz Selection Laguna.jpg",
    "lat": -23.63959,
    "lng": -46.71574
  },
  {
    "nome": "Vivaz Estação Pirituba",
    "bairro": "Pirituba",
    "endereco": "Avenida Cristo Rei, 34",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Próximo à estação da CPTM, amplo lazer.",
    "preco": "235mil",
    "entrega": "Nov/2028",
    "imagem": "assets/images/empreendimentos/Vivaz Estacao Pirituba.jpg",
    "lat": -23.48938,
    "lng": -46.72078
  },
  {
    "nome": "Vivaz Parque João Dias",
    "bairro": "Santo Amaro",
    "endereco": "Av. Maria Coelho Aguiar, 250",
    "area": "De 24m² a 38m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de vaga e varanda",
    "lazer": "Integração com áreas verdes e lazer completo.",
    "preco": "235mil",
    "entrega": "Out/2028",
    "imagem": "assets/images/empreendimentos/Vivaz Parque Joao Dias.jpg",
    "lat": -23.645962,
    "lng": -46.730015
  },
  {
    "nome": "Vivaz Connection  Adolfo Pinheiro",
    "bairro": "Santo Amaro",
    "endereco": "Rua Doutor Antônio Bento, 104",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "R. Dr Antônio Bento, 182",
    "preco": "244mil",
    "entrega": "Lançamento",
    "imagem": "assets/images/empreendimentos/Vivaz Connection.jpg",
    "lat": -23.6453481,
    "lng": -46.7021799
  },
  {
    "nome": "Vivaz Parque Freguesia do Ó (1, 2 e 3)",
    "bairro": "Freguesia do Ó",
    "endereco": "Rua Rio Verde, 1025",
    "area": "De 24m² a 45m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de vaga e varanda",
    "lazer": "Piscina, Academia, Churrasqueira, Coworking, Brinquedoteca.",
    "preco": "226mil",
    "entrega": "Out/2027",
    "imagem": "assets/images/empreendimentos/Vivaz Parque Freguesia do o.jpg",
    "lat": -23.4849018,
    "lng": -46.7011663
  },
  {
    "nome": "Vivaz Santa Marina",
    "bairro": "Água Branca",
    "endereco": "Avenida Santa Marina, 1660",
    "area": "De 31m² a 34m²",
    "quartos": "2",
    "diferenciais": "Opção de 1 vaga",
    "lazer": "Lazer completo, próximo ao Metrô e Shopping Bourbon.",
    "preco": "306mil",
    "entrega": "Jul/2027",
    "imagem": "assets/images/empreendimentos/Vivaz Santa Marina.jpg",
    "lat": -23.5027603,
    "lng": -46.6944346
  },
  {
    "nome": "Vivaz Cantareira (1, 2 e 3)",
    "bairro": "V. N. Cachoeirinha",
    "endereco": "Avenida Professor Miguel Franchini Neto, 186",
    "area": "34m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de 1 vaga e varanda",
    "lazer": "Localização próxima ao Horto Florestal, Lazer completo.",
    "preco": "293mil",
    "entrega": "Dez/2027",
    "imagem": "assets/images/empreendimentos/Vivaz Cantareira.jpg",
    "lat": -23.44355,
    "lng": -46.7253
  },
  {
    "nome": "Vivaz Estação Pirituba",
    "bairro": "Pirituba",
    "endereco": "Avenida Cristo Rei, 34",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Churrasqueiras, Playground, Fitness, Salão de Festas.",
    "preco": "209mil",
    "entrega": "Nov/2028",
    "imagem": "assets/images/empreendimentos/Vivaz Estacao Pirituba.jpg",
    "lat": -23.48938,
    "lng": -46.72078
  },
  {
    "nome": "Vivaz Prime Vila Prudente",
    "bairro": "Vila Prudente",
    "endereco": "Rua Cavour, 642",
    "area": "De 48m² a 56m²",
    "quartos": "2 a 3",
    "diferenciais": "Suíte, Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento superior e Lazer Completo",
    "preco": "537mil",
    "entrega": "Pronto",
    "imagem": "assets/images/empreendimentos/Vivaz Prime Vila Prudente.jpg",
    "lat": -23.5813085,
    "lng": -46.5762737
  },
  {
    "nome": "CASA PIAUÍ HIGIENÓPOLIS",
    "bairro": "HIGIENÓPOLIS",
    "endereco": "RUA PIAUÍ",
    "area": "249 - 255M²",
    "quartos": "4 Suítes",
    "diferenciais": "Suíte, Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "8 milhões e 500mil",
    "entrega": "Nov/2028",
    "imagem": "assets/images/empreendimentos/CASAPIAUI.png",
    "lat": -23.5465355,
    "lng": -46.6548677
  },
  {
    "nome": "HAVVA HIGIENÓPOLIS",
    "bairro": "HIGIENÓPOLIS",
    "endereco": "RUA BAHIA",
    "area": "352 - 641M²",
    "quartos": "4 Suítes",
    "diferenciais": "Suíte, Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "12 milhões",
    "entrega": "Fev/2029",
    "imagem": "assets/images/empreendimentos/HAVVA_Higienopolis.png",
    "lat": -23.5451366,
    "lng": -46.6597158
  },
  {
    "nome": "COLLAGE BELA VISTA",
    "bairro": "BELA VISTA",
    "endereco": "AV. BRIG LUIS ANTONIO",
    "area": "26 - 38m²",
    "quartos": "Studio e 1 Dorms",
    "diferenciais": "S/ Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "389mil",
    "entrega": "Nov/2028",
    "imagem": "assets/images/empreendimentos/COLLAGE BELA VISTA.png",
    "lat": -23.5605441,
    "lng": -46.6433462
  },
  {
    "nome": "PATTEO VILA MARIANA",
    "bairro": "VILA MARIANA",
    "endereco": "R: DOMINGOS DE MORAIS",
    "area": "26 - 33m²",
    "quartos": "Studio e 1 Dorms",
    "diferenciais": "S/ Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "509mil",
    "entrega": "Out/2027",
    "imagem": "assets/images/empreendimentos/PATTEO VILA MARIANA.png",
    "lat": -23.5785277,
    "lng": -46.6410318
  },
  {
    "nome": "PATTEO VILA MARIANA",
    "bairro": "VILA MARIANA",
    "endereco": "R: FRANÇA PINTO",
    "area": "91 - 125m²",
    "quartos": "2 e 3 Suítes",
    "diferenciais": "Suíte, Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "1 milhão e 75mil",
    "entrega": "Out/2027",
    "imagem": "assets/images/empreendimentos/PATTEO VILA MARIANA.png",
    "lat": -23.5876324,
    "lng": -46.6420424
  },
  {
    "nome": "OPEN MIND",
    "bairro": "CHÁCARA SANTO ANTONIO",
    "endereco": "R: ENXOVIA",
    "area": "32 - 122m²",
    "quartos": "1 ou 2 Dorms| Duplex| Studio",
    "diferenciais": "Suíte, Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "599mil",
    "entrega": "Jun/2027",
    "imagem": "assets/images/empreendimentos/OPEN MIND.png",
    "lat": -23.6288287,
    "lng": -46.6995339
  },
  {
    "nome": "ROYA PERDIZES",
    "bairro": "PERDIZES",
    "endereco": "R: DR HOMEM DE MELO",
    "area": "27 - 224m²",
    "quartos": "Studio|1 Dorm|4 Dorms",
    "diferenciais": "Suíte, Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "449mil",
    "entrega": "Jan/2027",
    "imagem": "assets/images/empreendimentos/ROYA PERDIZES.png",
    "lat": -23.5362131,
    "lng": -46.6698045
  },
  {
    "nome": "METROPOLITAN",
    "bairro": "VILA NOVA CONCEIÇÃO",
    "endereco": "R: JOÃO LOURENÇO",
    "area": "26 - 208m²",
    "quartos": "Studio| 2 ou 3 Suítes",
    "diferenciais": "Suíte, Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "739mil",
    "entrega": "Set/2026",
    "imagem": "assets/images/empreendimentos/METROPOLITAN.png",
    "lat": -23.5908681,
    "lng": -46.6677471
  },
  {
    "nome": "Caminhos da Lapa-Nova Vivere",
    "bairro": "Lapa",
    "endereco": "Rua Fortunato Ferraz 625",
    "area": "105m2",
    "quartos": "3 suites",
    "diferenciais": "Suíte, Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "1 milhão e 417mil",
    "entrega": "Mai/2026",
    "imagem": "assets/images/empreendimentos/Caminhos da Lapa-Nova Vivere.png",
    "lat": -23.5177726,
    "lng": -46.7178455
  },
  {
    "nome": "Caminhos da Lapa-Nova Vivere",
    "bairro": "Lapa",
    "endereco": "Rua Fortunato Ferraz 625",
    "area": "73m2",
    "quartos": "2 suite",
    "diferenciais": "Suíte, Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "892mil",
    "entrega": "Mai/2026",
    "imagem": "assets/images/empreendimentos/Caminhos da Lapa-Nova Vivere.png",
    "lat": -23.5177726,
    "lng": -46.7178455
  },
  {
    "nome": "Caminhos da Lapa - Garden design",
    "bairro": "Lapa",
    "endereco": "Rua Fortunato Ferraz 625",
    "area": "75m2",
    "quartos": "2 a 3",
    "diferenciais": "Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "725mil",
    "entrega": "Ago/2026",
    "imagem": "assets/images/empreendimentos/Caminhos da Lapa - Garden design.png",
    "lat": -23.5177726,
    "lng": -46.7178455
  },
  {
    "nome": "Signature",
    "bairro": "Barra Funda",
    "endereco": "Rua Robert Bosch, 332",
    "area": "44m, 45m e 58m",
    "quartos": "2 a 3",
    "diferenciais": "Varanda Grill, suíte, Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "579mil",
    "entrega": "Dez/2028",
    "imagem": "assets/images/empreendimentos/Signature.png",
    "lat": -23.521034,
    "lng": -46.6728561
  },
  {
    "nome": "Concept Barra Funda",
    "bairro": "Barra Funda",
    "endereco": "Rua Inocêncio Tobias, 130",
    "area": "36m a 61m",
    "quartos": "2",
    "diferenciais": "Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "338mil",
    "entrega": "Set/2028",
    "imagem": "assets/images/empreendimentos/Concept Barra Funda.png",
    "lat": -23.522686,
    "lng": -46.6726381
  },
  {
    "nome": "Abytá Santo Amaro",
    "bairro": "Santo Amaro",
    "endereco": "Rua Herbert Alfred Landsberger, 27",
    "area": "34m a 35m",
    "quartos": "2",
    "diferenciais": "Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "288mil",
    "entrega": "Dez/2028",
    "imagem": "assets/images/empreendimentos/Abyta Santo Amaro.png",
    "lat": -23.6618586,
    "lng": -46.7016056
  },
  {
    "nome": "Brooklin SKY",
    "bairro": "Brooklin",
    "endereco": "Rua Princesa Isabel, 400",
    "area": "26m a 58m",
    "quartos": "1",
    "diferenciais": "Garden e Up Garden",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "350mil",
    "entrega": "Ago/2028",
    "imagem": "assets/images/empreendimentos/Brooklin SKY.png",
    "lat": -23.6220072,
    "lng": -46.6827174
  },
  {
    "nome": "011 Brooklin",
    "bairro": "Brooklin",
    "endereco": "Rua Caetano José Batista, 149",
    "area": "40m a 65m",
    "quartos": "2",
    "diferenciais": "Garden, porcelanato",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "570mil",
    "entrega": "Dez/2028",
    "imagem": "assets/images/empreendimentos/011 Brooklin.png",
    "lat": -23.6214999,
    "lng": -46.6922873
  },
  {
    "nome": "Estilo Lapa",
    "bairro": "Lapa",
    "endereco": "Rua Fortunato Ferraz, 1251",
    "area": "25m a 45m",
    "quartos": "1 a 2",
    "diferenciais": "Varanda Grill, Vaga",
    "lazer": "Linha Prime: Acabamento Superior e Lazer Completo",
    "preco": "Aguarde Lançamento",
    "entrega": "Jan/2029",
    "imagem": "assets/images/empreendimentos/em-breve.png",
    "lat": -23.5177726,
    "lng": -46.7178455
  },
  {
    "nome": "Grand Vivaz Lapa",
    "bairro": "Lapa (Zona Oeste)",
    "endereco": "Rua Marina Ciufuli Zanfelice, 163",
    "area": "De 24m² a 39m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "churrasqueira, salão de festas, playground, coworking, academia, lavanderia e muito mais. Tudo planejado para proporcionar conforto e qualidade de vida aos moradores.\nCom localização estratégica, o Vivaz está a poucos minutos da Estação Lapa, que conecta diferentes linhas do metrô e trem, facilitando o deslocamento pela cidade.",
    "preco": "220mil",
    "entrega": "Mar/2029",
    "imagem": "assets/images/empreendimentos/Grand Vivaz Jardim Franca.jpg",
    "lat": -23.5132033,
    "lng": -46.707189
  }
];
