var EMPREENDIMENTOS = [
  {
    "nome": "Vivaz Penha 2",
    "bairro": "Penha (Zona Leste)",
    "endereco": "Avenida Condessa Elisabeth de Robiano, 6000",
    "area": "De 24m² a 38m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de vaga e varanda",
    "lazer": "Piscina, Academia, Espaço Camarote, Lavanderia, Minimercado.",
    "preco": "205mil",
    "entrega": "Nov/2028",
    "imagem": "imag/Vivaz Penha.jpg",
    "lat": -23.5300813,
    "lng": -46.5945978
  },
  {
    "nome": "Vivaz Freguesia do Ó",
    "bairro": "Freguesia (Zona Norte)",
    "endereco": "Avenida Itaberaba, 1234",
    "area": "De 24m² a 45m²",
    "quartos": "1 a 2",
    "diferenciais": "Próximo ao Metrô João Paulo I",
    "lazer": "Piscina, Coworking, Pet Place, Redário, Churrasqueira.",
    "preco": "226mil",
    "entrega": "Out/2027",
    "imagem": "imag/Vivaz Parque Freguesia do o.jpg",
    "lat": -23.4913555,
    "lng": -46.6947359
  },
  {
    "nome": "Vivaz Santo Amaro",
    "bairro": "Santo Amaro (Zona Sul)",
    "endereco": "Rua João Alfredo, 431",
    "area": "De 24m² a 40m²",
    "quartos": "2 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Piscina, Fitness, Salão de Games, Lavanderia, Brinquedoteca.",
    "preco": "218mil",
    "entrega": "Jan/2029",
    "imagem": "imag/Vivaz Santo Amaro.jpg",
    "lat": -23.6570072,
    "lng": -46.70044
  },
  {
    "nome": "Vivaz Estação Lapa",
    "bairro": "Lapa (Zona Oeste)",
    "endereco": "Rua Professor Clemente Pastore, 14",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Lazer completo, fácil acesso ao trem/terminal.",
    "preco": "214mil",
    "entrega": "Lançamento",
    "imagem": "imag/Vivaz Estacao Lapa.jpg",
    "lat": -23.51383,
    "lng": -46.69922
  },
  {
    "nome": "Grand Vivaz Penha",
    "bairro": "Penha (Zona Leste)",
    "endereco": "Avenida Condessa Elisabeth de Robiano, 5748",
    "area": "De 24m² a 38m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de vaga e varanda",
    "lazer": "Linha \"Grand\" com acabamentos diferenciados e lazer.",
    "preco": "235mil",
    "entrega": "Fev/2028",
    "imagem": "imag/Vivaz Penha.jpg",
    "lat": -23.5159,
    "lng": -46.5555
  },
  {
    "nome": "Grand Vivaz Estação Tamanduateí",
    "bairro": "Vila Prudente",
    "endereco": "Avenida Presidente Wilson, 4784",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Próximo ao Metrô e CPTM, lazer no condomínio.",
    "preco": "217mil",
    "entrega": "Dez/2028",
    "imagem": "imag/Grand Vivaz Estacao Tamanduatei.jpg",
    "lat": -23.5549432,
    "lng": -46.6110939
  },
  {
    "nome": "Grand Vivaz Jardim França Paris",
    "bairro": "Jardim França",
    "endereco": "Avenida Água Fria, 1215",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Localização residencial privilegiada na Zona Norte.",
    "preco": "224mil",
    "entrega": "Mai/2029",
    "imagem": "imag/Grand Vivaz Jardim Franca.jpg",
    "lat": -23.4780682,
    "lng": -46.6211741
  },
  {
    "nome": "Vivaz Selection Santo Amaro",
    "bairro": "Santo Amaro",
    "endereco": "Rua Doutor Rubens Gomes Bueno, 158",
    "area": "De 24m² a 40m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Localização estratégica próxima a centros comerciais.",
    "preco": "218mil",
    "entrega": "Jan/2029",
    "imagem": "imag/Vivaz Selection Santo Amaro.jpg",
    "lat": -23.6435906,
    "lng": -46.7189299
  },
  {
    "nome": "Vivaz Selection Laguna",
    "bairro": "Granja Julieta",
    "endereco": "Rua Laguna, 440",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de vaga e varanda",
    "lazer": "Próximo à Marginal Pinheiros e Parque Bruno Covas.",
    "preco": "235mil",
    "entrega": "Ago/2028",
    "imagem": "imag/Vivaz Selection Laguna.jpg",
    "lat": -23.63959,
    "lng": -46.71574
  },
  {
    "nome": "Vivaz Estação Pirituba",
    "bairro": "Pirituba",
    "endereco": "Avenida Cristo Rei, 34",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Próximo à estação da CPTM, amplo lazer.",
    "preco": "235mil",
    "entrega": "Nov/2028",
    "imagem": "imag/Vivaz Estacao Pirituba.jpg",
    "lat": -23.48938,
    "lng": -46.72078
  },
  {
    "nome": "Vivaz Parque João Dias",
    "bairro": "Santo Amaro",
    "endereco": "Av. Maria Coelho Aguiar, 250",
    "area": "De 24m² a 38m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de vaga e varanda",
    "lazer": "Integração com áreas verdes e lazer completo.",
    "preco": "235mil",
    "entrega": "Out/2028",
    "imagem": "imag/Vivaz Parque Joao Dias.jpg",
    "lat": -23.645962,
    "lng": -46.730015
  },
  {
    "nome": "Vivaz Connection  Adolfo Pinheiro",
    "bairro": "Santo Amaro",
    "endereco": "Rua Doutor Antônio Bento, 104",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "R. Dr Antônio Bento, 182",
    "preco": "244mil",
    "entrega": "Lançamento",
    "imagem": "imag/Vivaz Connection.jpg",
    "lat": -23.6453481,
    "lng": -46.7021799
  },
  {
    "nome": "Vivaz Parque Freguesia do Ó (1, 2 e 3)",
    "bairro": "Freguesia do Ó",
    "endereco": "Rua Rio Verde, 1025",
    "area": "De 24m² a 45m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de vaga e varanda",
    "lazer": "Piscina, Academia, Churrasqueira, Coworking, Brinquedoteca.",
    "preco": "226mil",
    "entrega": "Out/2027",
    "imagem": "imag/Vivaz Parque Freguesia do o.jpg",
    "lat": -23.4849018,
    "lng": -46.7011663
  },
  {
    "nome": "Vivaz Santa Marina",
    "bairro": "Água Branca",
    "endereco": "Avenida Santa Marina, 1660",
    "area": "De 31m² a 34m²",
    "quartos": "2",
    "diferenciais": "Opção de 1 vaga",
    "lazer": "Lazer completo, próximo ao Metrô e Shopping Bourbon.",
    "preco": "306mil",
    "entrega": "Jul/2027",
    "imagem": "imag/Vivaz Santa Marina.jpg",
    "lat": -23.5027603,
    "lng": -46.6944346
  },
  {
    "nome": "Vivaz Penha - Fase 3",
    "bairro": "Penha",
    "endereco": "Avenida Condessa Elisabeth de Robiano, 6000",
    "area": "De 24m² a 38m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de 1 vaga e varanda",
    "lazer": "Piscina, Salão de Jogos, Lavanderia coletiva, Quadra.",
    "preco": "235mil",
    "entrega": "Nov/2028",
    "imagem": "imag/Vivaz Penha.jpg",
    "lat": -23.5300813,
    "lng": -46.5945978
  },
  {
    "nome": "Vivaz Cantareira (1, 2 e 3)",
    "bairro": "V. N. Cachoeirinha",
    "endereco": "Avenida Professor Miguel Franchini Neto, 186",
    "area": "34m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de 1 vaga e varanda",
    "lazer": "Localização próxima ao Horto Florestal, Lazer completo.",
    "preco": "293mil",
    "entrega": "Dez/2027",
    "imagem": "imag/Vivaz Cantareira.jpg",
    "lat": -23.44355,
    "lng": -46.7253
  },
  {
    "nome": "Vivaz Connection Mooca",
    "bairro": "Mooca",
    "endereco": "Rua Sapucaia, 55",
    "area": "24m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Próximo a faculdades e Estação Juventus-Mooca.",
    "preco": "239mil",
    "entrega": "Fev/2028",
    "imagem": "imag/Vivaz Connection Mooca.jpg",
    "lat": -23.547048,
    "lng": -46.5941485
  },
  {
    "nome": "Vivaz Prime Voluntários da Pátria",
    "bairro": "Santana",
    "endereco": "Rua Voluntários da Pátria, 499",
    "area": "De 46m² a 61m²",
    "quartos": "2 a 3",
    "diferenciais": "Opção de varanda",
    "lazer": "Localização estratégica na Zona Norte, lazer elevado.",
    "preco": "523mil",
    "entrega": "Nov/2025",
    "imagem": "imag/Vivaz Prime Voluntarios da Patria.jpg",
    "lat": -23.5111488,
    "lng": -46.6261388
  },
  {
    "nome": "Vivaz Estação Pirituba (1 e 2)",
    "bairro": "Pirituba",
    "endereco": "Avenida Cristo Rei, 34",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Opção de varanda",
    "lazer": "Churrasqueiras, Playground, Fitness, Salão de Festas.",
    "preco": "209mil",
    "entrega": "Nov/2028",
    "imagem": "imag/Vivaz Estacao Pirituba.jpg",
    "lat": -23.48938,
    "lng": -46.72078
  },
  {
    "nome": "Vivaz Prime Vila Maria",
    "bairro": "Vila Maria",
    "endereco": "Rua Magarinos Torres, 480 - Vila Maria",
    "area": "55m²",
    "quartos": "2 a 3",
    "diferenciais": "Suíte e Varanda",
    "lazer": "Linha Prime: Acabamento superior, Piscina, Espaço Gourmet.",
    "preco": "525mil",
    "entrega": "Pronto",
    "imagem": "imag/Vivaz Prime Vila Maria.jpg",
    "lat": -23.5141602,
    "lng": -46.5913901
  },
  {
    "nome": "Vivaz Prime Vila Prudente",
    "bairro": "Vila Prudente",
    "endereco": "Rua Cavour, 642",
    "area": "De 48m² a 56m²",
    "quartos": "2 a 3",
    "diferenciais": "Suíte, Varanda e Vaga",
    "lazer": "Linha Prime: Acabamento superior, Piscina, Espaço Gourmet.",
    "preco": "537mil",
    "entrega": "Pronto",
    "imagem": "imag/Vivaz Prime Vila Prudente.jpg",
    "lat": -23.5813085,
    "lng": -46.5762737
  },
  {
    "nome": "Grand Vivaz Jardim França - Paris",
    "bairro": "Tucuruvi",
    "endereco": "Avenida Água Fria, 1215",
    "area": "De 24m² a 36m²",
    "quartos": "1 a 2",
    "diferenciais": "Suíte e Varanda",
    "lazer": "Churrasqueiras, Playground, Fitness, Salão de Festas.",
    "preco": "224mil",
    "entrega": "Lançamento",
    "imagem": "imag/Grand Vivaz Jardim Franca.jpg",
    "lat": -23.4780682,
    "lng": -46.6211741
  }
];